spring.data.mongodb.uri=mongodb+srv://madhubalagbu_db_user:3BcabpXGfrX9ynAG@cluster0.vs4ekty.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=..
#spring.data.mongodb.password=...
spring.data.mongodb.auto-index-creation=true
