spring:
  data:
    mongodb:
      uri: mongodb+srv://madhubalagbu_db_user:3BcabpXGfrX9ynAG@cluster0.vs4ekty.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal
